#!/usr/bin/env python

import logging
import click
import json

from hepbackends import MultiBackend, LocalBackend, GitBackend, NoneBackend
from hepbackends.webdav import WebDAVBackend
from hepbackends.xrootd import XRootdBackend


logging.basicConfig(
    format=u'(%(filename)s:%(lineno)d//%(levelname)s)\t%(message)s',
    level=logging.DEBUG
)
logging.getLogger("sh").setLevel(logging.ERROR)


# DCACHE_HOST = 'my.dcache.installation.with.webdav.com'
# DCACHE_PARAMS = {
#     'port': 2880,
# }

EOS_SERVER = "root://eoslhcb.cern.ch/"

BACKEND_MAP = {
    "local" : LocalBackend(),
    # "dcache": WebDAVBackend(DCACHE_HOST, DCACHE_PARAMS),
    "git": GitBackend(),
    "eos": XRootdBackend(EOS_SERVER),
    "none": NoneBackend(), # dummy one
}

backend = MultiBackend(BACKEND_MAP)


@click.command(help='Downloads data to somewhere')
@click.argument('src', nargs=1)
@click.argument('dst', nargs=1)
def main(src, dst):
    with open(src) as srcfile:
        input_files = json.load(srcfile)

    for input_file in input_files:
        logging.debug("Downloading `{}` to `{}`".format(input_file, dst))
        backend.copy_from_backend(input_file, dst)


if __name__ == '__main__':
    main()